import turtle
import time
print('Imported')

#BASICS
print('Drawing a square with a red outline and a brown fill...')
turtle.fillcolor('brown')
turtle.begin_fill()
turtle.pencolor('red')
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.end_fill()
time.sleep(1)
print('Drawing a square with sides of 180, a purple outline and a red fill...')
turtle.reset()
turtle.fillcolor('red')
turtle.pencolor('purple')
turtle.begin_fill()
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.end_fill()
time.sleep(1)
print('Drawing a rectangle...')
turtle.reset()
turtle.forward(150)
turtle.right(90)
turtle.forward(80)
turtle.right(90)
turtle.forward(150)
turtle.right(90)
turtle.forward(80)
print('Drawing another rectangle...')
turtle.penup()
turtle.forward(50)
turtle.pendown()
turtle.pencolor('red')
turtle.fillcolor('orange')
turtle.begin_fill()
turtle.forward(150)
turtle.right(90)
turtle.forward(80)
turtle.right(90)
turtle.forward(150)
turtle.right(90)
turtle.forward(80)
turtle.end_fill()
time.sleep(1)
print('Drawing a triangle...')
turtle.reset()
turtle.forward(150)
turtle.right(120)
turtle.forward(150)
turtle.right(120)
turtle.forward(150)
turtle.right(120)
print('Drawing a pentagon and a decagon...')
turtle.reset()
turtle.pencolor('green')
turtle.fillcolor('hotpink')
turtle.begin_fill()
for x in range(5):
	turtle.forward(100)
	turtle.left(72)
turtle.end_fill()
turtle.pencolor('red')
turtle.fillcolor('beige')
turtle.penup()
turtle.forward(230)
turtle.pendown()
turtle.begin_fill()
for x in range(10):
	turtle.forward(100)
	turtle.left(36)
turtle.end_fill()
time.sleep(1)

#REPEATING INSTRUCTIONS
print('Drawing four squares...')
turtle.reset()
def drawSquare(size):
  for x in range(4):
      turtle.fd(size)
      turtle.lt(90)
turtle.penup()
turtle.fd(150)
turtle.pendown()
drawSquare(100)
turtle.penup()
turtle.fd(150)
turtle.pendown()
drawSquare(100)
turtle.penup()
turtle.fd(150)
turtle.pendown()
drawSquare(100)
turtle.penup()
turtle.fd(150)
turtle.pendown()
drawSquare(100)
print('Drawing a star...')
turtle.reset()
def drawStar():
	for x in range(5):
		turtle.forward(100)
		turtle.left(144)
print('Drawing four stars...')
turtle.penup()
turtle.fd(150)
turtle.pendown()
drawStar()
turtle.penup()
turtle.fd(150)
turtle.pendown()
drawStar()
turtle.penup()
turtle.fd(150)
turtle.pendown()
drawStar()
turtle.penup()
turtle.fd(150)
turtle.pendown()
drawStar()
print('Drawing a square pattern...')
drawSquare(100)
drawSquare(90)
drawSquare(80)
drawSquare(70)
drawSquare(60)
drawSquare(50)
drawSquare(40)
drawSquare(30)
drawSquare(20)
drawSquare(10)

#Subroutines/Functions
print('Drawing 3 squares using functions...')
def nextShape(x):
	turtle.pu()
	turtle.fd(x)
	turtle.pd()
drawSquare(100)
nextShape(150)
drawSquare(100)
nextShape(150)
drawSquare(100)
turtle.reset()
print('Drawing 10 squares using functions and a for loop...')
turtle.goto(-0,-0)
for x in range(10):
	drawSquare(200)
	nextShape(250)
time.sleep(5)
print('Program finished!')
